export const labelList = [
	{
		id: 100121,
		shippingTypeId: 1,
		customerName: 'Luis',
		customerLastName: 'Urrieta',
		customerId: 30289122,
		customerPhone: 1137255121,
		addressStreet: 'Av. Juan B. Justo',
		addressStreetNumber: 1536,
		addressFloor: '6',
		postalCode: '1216',
		neighbourhood: 'Palermo',
		city: 'Capital Federal',
		province: 'Buenos Aires'
	},
	{
		id: 100122,
		shippingTypeId: 2,
		customerName: 'Ramiro',
		customerLastName: 'Ochoa',
		customerId: 18244373,
		customerPhone: 1156412820,
		addressStreet: 'Av. Boedo',
		addressStreetNumber: 236,
		addressFloor: '2b',
		postalCode: '1190',
		neighbourhood: 'Boedo',
		city: 'Capital Federal',
		province: 'Buenos Aires'
	},
	{
		id: 100123,
		shippingTypeId: 1,
		customerName: 'Julieta',
		customerLastName: 'Bebaqua',
		customerId: 38174169,
		customerPhone: 29543765575,
		addressStreet: 'Av. San Martin',
		addressStreetNumber: 2326,
		addressFloor: '',
		postalCode: '7562',
		neighbourhood: 'Santa Rosa',
		city: 'Santa Rosa',
		province: 'La Pampa'
	},
	{
		id: 100124,
		shippingTypeId: 3,
		customerName: 'Eugenio',
		customerLastName: 'Mallaviabarrena',
		customerId: 36976822,
		customerPhone: 1135724069,
		addressStreet: '',
		addressStreetNumber: 0,
		addressFloor: '',
		postalCode: '',
		neighbourhood: '',
		city: '',
		province: ''
	},
	{
		id: 100125,
		shippingTypeId: 3,
		customerName: 'Maria Emilia',
		customerLastName: 'Fuentes',
		customerId: 26535207,
		customerPhone: 1152910129,
		addressStreet: '',
		addressStreetNumber: 0,
		addressFloor: '',
		postalCode: '',
		neighbourhood: '',
		city: '',
		province: ''
	},
	{
		id: 100126,
		shippingTypeId: 2,
		customerName: 'Josefina',
		customerLastName: 'Manueco',
		customerId: 30915442,
		customerPhone: 1139284712,
		addressStreet: 'Necochea',
		addressStreetNumber: 842,
		addressFloor: '17D',
		postalCode: '1065',
		neighbourhood: 'Belgrano',
		city: 'Capital Federal',
		province: 'Buenos Aires'
	},
	{
		id: 100127,
		shippingTypeId: 1,
		customerName: 'Daniela',
		customerLastName: 'Battaglia',
		customerId: 25762316,
		customerPhone: 37925369914,
		addressStreet: 'Rivadavia',
		addressStreetNumber: 316,
		addressFloor: '',
		postalCode: '7607',
		neighbourhood: 'Centro',
		city: 'Corrientes',
		province: 'Corrientes'
	}
];
